using MalbersAnimations.Utilities;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public class ColorPickerCreator : MonoBehaviour
{
    public GameObject colorPickerPrefab;
    public Color[] colors;
}

[CustomEditor(typeof(ColorPickerCreator))]
public class ColorPickerCreatorEditor : Editor
{
    public override void OnInspectorGUI()
    {
        base.OnInspectorGUI();
        if (GUILayout.Button("Fill Content"))
        {
            ColorPickerCreator creator = (ColorPickerCreator)target;
            FillContent(creator);
            // Save changes
            EditorUtility.SetDirty(creator);

        }


    }
    public void FillContent(ColorPickerCreator creator)
    {
        // This method can only be called in Editor
        if (!Application.isEditor)
        {
            Debug.LogWarning("This method can only be called in Editor");
            return;
        }

        Transform parent = creator.transform;
        ToggleGroup toggleGroup = creator.GetComponent<ToggleGroup>();
        int destroyCount = 0;
        Transform[] children = new Transform[parent.childCount];
        for (int i = 0; i < parent.childCount; i++)
        {
            children[i] = parent.GetChild(i);
        }
        
        // Clear content
        foreach (Transform child in children)
        {
            DestroyImmediate(child.gameObject);
            destroyCount++;
        }
        // Print Destroyed Object count
        Debug.Log($"Destroyed {destroyCount} objects");
        // Fill content
        foreach (Color color in creator.colors)
        {
            GameObject colorPicker = Instantiate(creator.colorPickerPrefab, parent);
            colorPicker.name = creator.colorPickerPrefab.name + "_AUTOGENERATED";
            colorPicker.GetComponentInChildren<Image>().color = color;
            colorPicker.GetComponent<Toggle>().group = toggleGroup;
            // Save chagnes
            EditorUtility.SetDirty(colorPicker);
        }
        Debug.Log($"Created {creator.colors.Length} objects");
    }
}
